"""create inventory and sync tables

Revision ID: ca2c9afa5eb7
Revises: 3bd67eab8293
Create Date: 2026-04-28 18:24:26.459698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca2c9afa5eb7'
down_revision: Union[str, Sequence[str], None] = '3bd67eab8293'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_tenant_id'), 'locations', ['tenant_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sku_code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=50), nullable=False),
    sa.Column('unit_cost_paise', sa.BigInteger(), nullable=False),
    sa.Column('selling_price_paise', sa.BigInteger(), nullable=False),
    sa.Column('industry_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'sku_code', name='uq_tenant_sku')
    )
    op.create_index(op.f('ix_products_tenant_id'), 'products', ['tenant_id'], unique=False)
    op.create_table('sync_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('connector_type', sa.String(length=50), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('stored_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('records_failed', sa.Integer(), nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_quality_score', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_logs_tenant_id'), 'sync_logs', ['tenant_id'], unique=False)
    op.create_index('ix_sync_logs_tenant_status', 'sync_logs', ['tenant_id', 'status'], unique=False)
    op.create_table('batches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('batch_no', sa.String(length=100), nullable=False),
    sa.Column('manufactured_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'batch_no', 'product_id', name='uq_tenant_batch_product')
    )
    op.create_index(op.f('ix_batches_tenant_id'), 'batches', ['tenant_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('unit_cost_paise', sa.BigInteger(), nullable=False),
    sa.Column('reference_no', sa.String(length=100), nullable=True),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transactions_tenant_date', 'transactions', ['tenant_id', sa.literal_column('transaction_date DESC')], unique=False)
    op.create_index(op.f('ix_transactions_tenant_id'), 'transactions', ['tenant_id'], unique=False)
    op.create_index('ix_transactions_tenant_location', 'transactions', ['tenant_id', 'location_id'], unique=False)
    op.create_index('ix_transactions_tenant_product', 'transactions', ['tenant_id', 'product_id'], unique=False)
    op.create_index('ix_transactions_tenant_type', 'transactions', ['tenant_id', 'transaction_type'], unique=False)
    op.execute('ALTER TABLE locations ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE locations FORCE ROW LEVEL SECURITY')
    op.execute('CREATE POLICY tenant_isolation_locations ON locations FOR ALL TO nexus_runtime USING (tenant_id = app.current_tenant_id()) WITH CHECK (tenant_id = app.current_tenant_id())')
    op.execute('ALTER TABLE products ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE products FORCE ROW LEVEL SECURITY')
    op.execute('CREATE POLICY tenant_isolation_products ON products FOR ALL TO nexus_runtime USING (tenant_id = app.current_tenant_id()) WITH CHECK (tenant_id = app.current_tenant_id())')
    op.execute('ALTER TABLE sync_logs ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE sync_logs FORCE ROW LEVEL SECURITY')
    op.execute('CREATE POLICY tenant_isolation_sync_logs ON sync_logs FOR ALL TO nexus_runtime USING (tenant_id = app.current_tenant_id()) WITH CHECK (tenant_id = app.current_tenant_id())')
    op.execute('ALTER TABLE batches ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE batches FORCE ROW LEVEL SECURITY')
    op.execute('CREATE POLICY tenant_isolation_batches ON batches FOR ALL TO nexus_runtime USING (tenant_id = app.current_tenant_id()) WITH CHECK (tenant_id = app.current_tenant_id())')
    op.execute('ALTER TABLE transactions ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE transactions FORCE ROW LEVEL SECURITY')
    op.execute('CREATE POLICY tenant_isolation_transactions ON transactions FOR ALL TO nexus_runtime USING (tenant_id = app.current_tenant_id()) WITH CHECK (tenant_id = app.current_tenant_id())')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP POLICY IF EXISTS tenant_isolation_transactions ON transactions')
    op.execute('ALTER TABLE transactions NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE transactions DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_batches ON batches')
    op.execute('ALTER TABLE batches NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE batches DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_sync_logs ON sync_logs')
    op.execute('ALTER TABLE sync_logs NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE sync_logs DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_products ON products')
    op.execute('ALTER TABLE products NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE products DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_locations ON locations')
    op.execute('ALTER TABLE locations NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE locations DISABLE ROW LEVEL SECURITY')
    op.drop_index('ix_transactions_tenant_type', table_name='transactions')
    op.drop_index('ix_transactions_tenant_product', table_name='transactions')
    op.drop_index('ix_transactions_tenant_location', table_name='transactions')
    op.drop_index(op.f('ix_transactions_tenant_id'), table_name='transactions')
    op.drop_index('ix_transactions_tenant_date', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_batches_tenant_id'), table_name='batches')
    op.drop_table('batches')
    op.drop_index('ix_sync_logs_tenant_status', table_name='sync_logs')
    op.drop_index(op.f('ix_sync_logs_tenant_id'), table_name='sync_logs')
    op.drop_table('sync_logs')
    op.drop_index(op.f('ix_products_tenant_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_locations_tenant_id'), table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
